working_directory: ~/repo
docker:
  - image: circleci/node:12.18
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_TOKEN
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Run unit tests on OVM compiled output (TODO enable tests)
      command: |
        npx buidler compile --use-ovm --optimizer
